# fly.toml app configuration file generated for lager-kumpel on 2024-08-22T22:13:39+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'lager-kumpel'
primary_region = 'ams'

[build]

[env]
  MONGODB_PASSWORD = 'Z8O88F2NGA8Y2aoG'
  MONGODB_URI = 'mongodb+srv://kbozinovic8:Z8O88F2NGA8Y2aoG@cluster0.hffngtv.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0'
  PORT = '3000'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
