
###
GET https://backend-delicate-dust-7996.fly.dev/api/boxes/1

###
POST http://localhost:3003/api/boxes
Content-Type: application/json

{
    "number":3
}

###
PUT http://localhost:3003/api/boxes/1/reset

