GET http://localhost:3000/api/orders

###
GET http://localhost:3000/api/orders/month

###
GET http://localhost:3000/api/orders/grouped_by_country?timePeriod=year

###
GET http://localhost:3000/api/orders/count?timePeriod=month&processed=true

###

GET http://localhost:3000/api/orders/revenue?timePeriod=today


###
POST http://localhost:3000/api/orders
Content-Type: application/json

{
    "customerName":"Dominik Bozinovic",
    "items": [{"barcode":"22","quantity":1}, {"barcode":"24","quantity":1}, {"barcode":"23","quantity":1}]
}


###
GET http://localhost:3000/api/orders/0000009

###
GET http://localhost:3000/api/orders/processed

###
GET http://localhost:3000/api/orders/unprocessed

###
GET http://localhost:3000/api/orders/in_picklist

###
GET http://localhost:3000/api/orders/not_in_picklist



###
PATCH http://localhost:3000/api/orders/0000009/processed
###
PATCH http://localhost:3000/api/orders/0000009/in_picklist


